### ISSUE TITLE
Unable to download pre-trained ViT.pth models, need to request

### ISSUE THREAD

**Issue by guijuzhejiang** [zin-Fu/Tongue-Segmentation-and-classification#2]
Thanks for your work,  I intend to use the models you provided, but the download requires a request to be submitted, which I submitted, but it never went through. Can you please pass my download request?

**Comment by zin-Fu** [comment]
Hi,thanks for your attention and sorry for the confusion, I have set the permissions for everyone to download. This problem should be solved by now！😁

**Comment by guijuzhejiang** [comment]
Great. Thank you.

**Comment by KxLin-sp66** [comment]
Great
